FROM composer:2 AS dependencies

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-interaction --no-progress --optimize-autoloader


FROM dunglas/frankenphp:1-php8.4-alpine

WORKDIR /app

RUN install-php-extensions mongodb

COPY --from=dependencies /app/vendor ./vendor

COPY Caddyfile /etc/caddy/Caddyfile

COPY . .

ENV PORT=80

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]